spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: sandbox
  main:
    allow-circular-references: true

logging:
  level:
#    org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG
    org.springframework.data.cassandra: DEBUG